name       : python-h11
version    : 0.13.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/h/h11/h11-0.13.0.tar.gz : 70813c1135087a248a4d38cc0e1a0181ffab2188141a93eaf567940c3957ff06
license    : MIT
component  : programming.python
summary    : A pure-Python, bring-your-own-I/O implementation of HTTP/1.1
description: |
    This is a little HTTP/1.1 library written from scratch in Python, heavily inspired by hyper-h2.
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
